# Generated by Django 5.1.1 on 2024-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories//%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, null=True, upload_to='products/large/%Y/%m/%d', verbose_name='Большое фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, null=True, upload_to='products/medium/%Y/%m/%d', verbose_name='Среднее фото'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, null=True, upload_to='products/small/%Y/%m/%d', verbose_name='Маленькое фото'),
        ),
    ]
