# Generated by Django 5.1.1 on 2024-09-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
